apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapps-acme
  namespace: app-gitops
spec:
  sourceNamespaces:
  - myapps-acme
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'hello-openshift'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
